export { default as Hero } from './Hero'
export { default as Project } from './Project'
export { default as Contact } from './Contact'
export { default as Features } from './Features'
export { default as TimeLine } from './TimeLine'
