export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Features } from './Features'
export { default as TimeLine } from './TimeLine'
